name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        include:
          - os: ubuntu-24.04
            target: aarch64-unknown-linux-musl
            target_alias: linux-arm64
    defaults:
      run:
        shell: bash
    env:
      ARCHIVE_PATH: encrypted-dns_${{ github.ref_name }}_${{ matrix.target_alias }}${{ matrix.archive_suffix }}

    steps:
      - uses: actions/checkout@v4

      - name: Install cross for cross compile
        run: |
          cargo install cross --git https://github.com/cross-rs/cross

      #- name: Install musl source
      #  run: sudo apt install -y musl-dev

      - name: Set Rustup target
        run: rustup target add aarch64-unknown-linux-musl

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: aarch64-unknown-linux-musl
            override: true
            profile: minimal
            components: rustfmt     

      - name: Check Cargo availability
        run: cargo --version

      - name: Check Rustup default toolchain
        run: rustup default | grep stable

      - name: Build
        run: |
          echo 'lto = "fat"' >> Cargo.toml
          env RUSTFLAGS="-C strip=symbols" cross build --release --target=aarch64-unknown-linux-musl
          mkdir encrypted-dns
          cp target/aarch64-unknown-linux-musl/release/encrypted-dns${{ matrix.bin_suffix }} encrypted-dns/
          cp README.md example-encrypted-dns.toml encrypted-dns/
          tar cjpf ${ARCHIVE_PATH} encrypted-dns

      - uses: actions/upload-artifact@v4
        with:
          name: encrypted-dns_${{ matrix.target_alias }}
          path: ${{ env.ARCHIVE_PATH }}

